name: Bridge
version: '${project.version}'
main: me.lagggpixel.bridge.Bridge
api-version: 1.8
authors: [ Lagggpixel ]
description: Bridge Plugin
softdepend: ['Multiverse-Core']
commands:
  bridge:
    description: Primary command
    usage: /bridge
  play:
    description: Join a game
    usage: /play
