name: Bridge
version: '0.0'
main: me.lagggpixel.bridge.Bridge
api-version: 1.8
authors: [ Lagggpixel ]
description: Bridge Plugin
softdepend: ['Multiverse-Core']
commands:
  bridge:
    description: Used for a variety of things
    usage: /bridge help
  play:
    description: Join a game
    usage: /play
